### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by BenjiTheC** [Trinkle23897/tuixue.online-visa#36]
I just found out 5 minutes ago that connection tuixue.online is considered "not private". This is possibly due to the expiration of SSL certificate.

**Chrome**:

<img width="1097" alt="Screen Shot 2020-10-08 at 21 16 25" src="https://user-images.githubusercontent.com/42496006/95472232-f981f280-09ac-11eb-97aa-5f858f2adfea.png">

**Safari macOS**:

<img width="784" alt="Screen Shot 2020-10-08 at 21 20 48" src="https://user-images.githubusercontent.com/42496006/95472250-fdae1000-09ac-11eb-8a39-625701259f4d.png">

**Safari iOS**:

![IMG_1921](https://user-images.githubusercontent.com/42496006/95472369-259d7380-09ad-11eb-8dd4-390f8c060085.PNG)

**Comment by Trinkle23897** [comment]
fixed
```
letsencrypt renew
service nginx restart
```
