### ISSUE TITLE
请教一下技术问题：如何获取签证的预约时间

### ISSUE THREAD

**Issue by Celthi** [Trinkle23897/tuixue.online-visa#45]
@Trinkle23897 你好，因为签证问题想自己写一个类似的爬虫，搜了一下，发现大佬你已经写好了！果断用用了！微信刚刚转了个红包表示感谢！
请问你是如何获取签证的预约时间（虽然不用自己写了，但是还是求知一下）？

1. 注册一个随机的用户，然后用这个用户去访问可以查看预约时间的页面，获取预约时间。
2. 用一个特定的用户去访问可以查看预约时间的页面。
3. 有一个页面可以获取预约的时间，不需要注册用户。

我大致看了一下代码，这里好像有注册随机用户的地方https://github.com/Trinkle23897/tuixue.online-visa/blob/0428b2472a98643c4588a84f805f39b972818ff2/visa2/visa.py#L46
所以请问是不是方法1？
我浏览相应的issues，发现你们 https://github.com/Trinkle23897/tuixue.online-visa/issues/35 提到一个ais.json,请问这个是用于做什么的？

**Comment by Trinkle23897** [comment]
cgi系统是1，ais系统是2，3不存在

**Comment by Celthi** [comment]
> cgi系统是1，ais系统是2，3不存在

请问cgi和ais系统的区别是什么？

**Comment by Trinkle23897** [comment]
国内都是cgi系统，就预约签证网址开头是cgi；国外像欧洲，北美南美都是ais系统，其他地方是cgi

**Comment by Celthi** [comment]
> 国内都是cgi系统，就预约签证网址开头是cgi；国外像欧洲，北美南美都是ais系统，其他地方是cgi

原来如此，也就是说ais系统需要ais.json来登录访问预约界面，cgi系统随机注册用户访问预约界面,对吗~

**Comment by Trinkle23897** [comment]
yep

**Comment by Celthi** [comment]
Thanks a ton. @Trinkle23897 I'll close this issue.
