### ISSUE TITLE
想问一下穿透通知是怎么通知的

### ISSUE THREAD

**Issue by Yiyiyimu** [Trinkle23897/tuixue.online-visa#47]
再次感谢这么棒的项目！！想问一下穿透通知是会跳 windows notification 吗

**Comment by Trinkle23897** [comment]
我拿edge试了下，看右下角

![2021-02-24 19-55-40 的屏幕截图](https://user-images.githubusercontent.com/8189182/108997259-553de580-76da-11eb-9f10-f360baca665e.png)

**Comment by Yiyiyimu** [comment]
不好意思这个是需要点什么地方开启吗，看到只有邮件可以设置订阅，没找到开自动通知的地方

**Comment by Trinkle23897** [comment]
我做了默认开的……正常来说如果浏览器支持这个功能的话，他会在第一次（或者（跳出是否允许通知时）没有点击“否”）会跳出“是否允许tuixue.online”通知
我待会儿写一写手动通知的测试，不过如果只有浏览器的权限的话，从网站的角度是没办法做到修改已经被ban掉的通知选项，得进入浏览器的设置-通知里面把tuixue放出来

**Comment by Trinkle23897** [comment]
Here it is: https://tuixue.online/notification

**Comment by Yiyiyimu** [comment]
感谢感谢！notification work的，我这边是chrome自动禁止通知的。。
