### ISSUE TITLE
肯尼亚（AIS)系统的爬虫

### ISSUE THREAD

**Issue by kikiyang** [Trinkle23897/tuixue.online-visa#63]
太感谢你们的工作了！！请问如果想在你们的基础上开发针对肯尼亚（AIS)系统的爬虫，从哪里开始比较好呢？有文档参考吗？感谢！！！🙏

**Comment by Trinkle23897** [comment]
逻辑都写好了，现在是如何绕过它的登录验证的问题，ais从5月开始会经常封爬虫服务器的ip

**Comment by kikiyang** [comment]
感谢！
