### ISSUE TITLE
邮件提醒订阅不成功

### ISSUE THREAD

**Issue by 2uanj1e** [Trinkle23897/tuixue.online-visa#67]
网页上温哥华领馆的B2签证一直没有数据，订阅邮件提醒也没有收到确认

**Comment by Trinkle23897** [comment]
加拿大是ais，ais爬虫挂了好久了……

**Comment by 2uanj1e** [comment]
谢谢，所以现在只能自己部署吗？

**Comment by Trinkle23897** [comment]
不是，问题在于他会封ip然后我们并没有找到好的解决方案（也许挂个vpn ip pool就好了……？）

**Comment by 2uanj1e** [comment]
谢谢

**Comment by Jilda1987** [comment]
About system AIS, u can use prepaid use approximately 40, change ip.
