### ISSUE TITLE
where does node.txt come from

### ISSUE THREAD

**Issue by ruotianluo** [Trinkle23897/tuixue.online-visa#70]
你好，我想着直接调用ais_reg和ais_refersh，但是我发现webdriver会报错在这里https://github.com/Trinkle23897/tuixue.online-visa/blob/master/api/tuixue/ais_reg.py#L36.

请问这个node.txt是怎么来的。我怎么才能生成这样一个node.txt。

谢谢。

**Comment by Trinkle23897** [comment]
可以本地起一个api服务，然后node.txt里面写localhost的端口就行
