### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by KangLiao929** [Trinkle23897/tuixue.online-visa#71]
Hi, thanks for such a nice tool. My friends got the visa appointment successfully one month ago.

But in the recent two weeks, I and some friends cannot receive any email notifications. My appointment is for B1/B2 in Germany.

Could you please help us to check the email notifications?

Thanks.

**Comment by Trinkle23897** [comment]
It's because cgi website use gCaptcha on Apr 15th. The crawler has not been adapted to it yet. We are handling with this issue these days (with 2captcha) and if everything goes well, it should be back in a few days.

**Comment by KangLiao929** [comment]
Thanks a lot. We appreciate your help!

**Comment by Trinkle23897** [comment]
should work now.
