### ISSUE TITLE
Add Poland (Warsaw and Krakow) to the list of CGI conulates

### ISSUE THREAD

**Issue by virtuman** [Trinkle23897/tuixue.online-visa#76]
Hello, I would gladly make a pull request, but I don't see where I could pull consulate codes for Poland's Krakow and Warsaw cities.

Thank you

**Comment by Trinkle23897** [comment]
I'll do that.

**Comment by Trinkle23897** [comment]
Just added. You can check the website:
<img width="1440" alt="截屏2022-05-29 下午10 10 29" src="https://user-images.githubusercontent.com/8189182/170915647-a16f5a74-c088-414a-bad9-a4d19f58a124.png">
