### ISSUE TITLE
Notification is broken

### ISSUE THREAD

**Issue by sch0107** [Trinkle23897/tuixue.online-visa#79]
Notification, both the email and website one seems not working.
Tried on hotmail.com and outlook.com, for B1/B2

**Comment by JA030019** [comment]
Also find this problem

**Comment by JavaDevAliens** [comment]
yes it is not working for me as well

**Comment by JavaDevAliens** [comment]
@Trinkle23897

**Comment by JavaDevAliens** [comment]
@Trinkle23897 i wanted to contribute from my end can you please explain how do i setup this, in local machine

**Comment by Trinkle23897** [comment]
> Notification, both the email and website one seems not working.

For email, try qq/163. What's the problem of website notification?

> how do i setup this, in local machine

I believe the instructions are in README file written in English. Please check that.
